#! /usr/bin/env bash

# -6dB dimmer
# dim/restore volume of playing clients.

declare volfile="$HOME/.config/speaker.volume"

__help() {
cat << 'EOB' >&2
Vdim: -6dB dimmer for pulseaudio default sink.

Usage:
  vdim          - dim/undim default sink.
  vdim h | help - show this help and exit.

EOB
}

dim() {
  local info index go r1 r2 r3 vol
  r1="^\* index:[[:space:]]*(.+)$"
  r2="^used by:[[:space:]]*(.+)$"
  r3="^volume:[[:space:]]*front\-left:[[:space:]]*([0-9]+).*$"
  while read -r info; do
    [[ $info =~ $r1 ]] && {
      # default sink index
      index="${BASH_REMATCH[1]}"
      go=1
      continue
    }
    [[ $go ]] && {
      [[ $info =~ $r3 ]] && {
        # current volume
        vol="${BASH_REMATCH[1]}"
        [[ -a "$volfile" ]] && saved_vol="$(<"$volfile")" || saved_vol=0
        continue
      }
      [[ $info =~ $r2 ]] && {
        # are there any active clients?
        if [[ ${BASH_REMATCH[1]} -gt 0 ]]; then
          # dim default sink and save current volume.
          if ((vol>saved_vol)); then
            pacmd set-sink-volume $((index)) $((vol/2))
            echo "$vol" > "$volfile"
            echo "dimmed."
            return 0
          fi
       fi
       if ((vol<saved_vol)); then
         # restore saved volume
         pacmd set-sink-volume $((index)) $((saved_vol))
         :> "$volfile"
         echo "restored."
         return 0
       fi
       echo "nothing to do."
       return 0
    }
  }
  done < <(pacmd list-sinks)
  return 1
}

[[ $1 == "h" || $1 == "help" ]] && {
  __help;
  exit 0
}

dim || echo "[!] there was an error."
